### ISSUE TITLE
e1000: add driver support for Intel I219V

### ISSUE THREAD

**Issue by Benqer0** [opnsense/src#110]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

**Describe the solution you like**

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

Please add the driver functionalities for this LAN adapter.

https://bsd-hardware.info/?id=pci:8086-15fa-1849-15fa

https://www.intel.de/content/www/de/de/products/network-io/ethernet/controllers/gigabit-ethernet-controllers/connection-i219-v.html

Thank you!

**Comment by rakaur** [comment]
I have this same issue. It was a problem in FreeBSD12 and was patched in either a 12 point release or 13. It works fine in current pfsense, and current HardenedBSD-13. I'm not exactly sure when it was fixed but it's definitely fixed in upstream.

I very much want to migrate from pfsense to opnsense but I cannot until this driver problem is resolved.

**Comment by fichtner** [comment]
TBH, „either there or here“ is not helpful. I went looking in FreeBSD stable/12 and at least the device the OP was kind enough to give information about is not supported there. We still use FreeBSD 12(.1) so whatever some other projects do is not so much relevant. ;)

And that FreeBSD bug report is from 2019 and already included in 12.1 and therefore OPNsense 20.7 and 21.1. Please don’t post random reports that are not verifiable due to lack of information you chose to provide.


Cheers,
Franco

**Comment by fichtner** [comment]
Ok, sorry I responded to the mail but there is some info edited in now. You are looking for https://github.com/opnsense/src/commit/249cd0c312f5db6a8567d5ccb772facd925f0f9f which was picked up yesterday. It will be part of 21.7 release in July.

**Comment by rakaur** [comment]
You could have asked me for anything information you needed. I am not an OPNsense developer. I gave you the information I was able to figure out on my own, and offered what I had in an attempt to be helpful. Next time would you prefer if I don't report the problem at all and continue using your competition?

**Comment by fichtner** [comment]
> You could have asked me for anything information you needed. I am not an OPNsense developer. I gave you the information I was able to figure out on my own, and offered what I had in an attempt to be helpful. Next time would you prefer if I don't report the problem at all and continue using your competition?

You are not a developer and I am not a fortune teller. All I can say is if you want something done you have to improve your communication skills and avoid irrelevant bug reports. ;)

**Comment by rakaur** [comment]
People like you are why people don't bother filing bug reports for open source software.

**Comment by fichtner** [comment]
Kind of trollish to say this in another person's request for help after both your request and the original poster's request have been put into perspective for 21.7, but, yeah, you still do need to practice your communication and social skills. :)


Cheers,
Franco

**Comment by rakaur** [comment]
Why yes, it was fixed, probably as a direct result of this thread. And yet you spent the entire time insulting my bug report.

**Comment by fichtner** [comment]
> Why yes, it was fixed, probably as a direct result of this thread. And yet you spent the entire time insulting my bug report.

Wow, this is delusional. When I said "yesterday" I literally meant yesterday and all your poor behaviour is wasted time for the both of us.

<img width="944" alt="Screenshot 2021-04-25 at 7 47 27 PM" src="https://user-images.githubusercontent.com/1915288/116003704-5b2f4480-a5ff-11eb-952e-823f37443146.png">

<img width="705" alt="Screenshot 2021-04-25 at 7 47 08 PM" src="https://user-images.githubusercontent.com/1915288/116003714-61bdbc00-a5ff-11eb-965e-361f529928f0.png">

**Comment by fichtner** [comment]
Note: This thread won't be locked but all irrelevant answers will be marked as spam.

**Comment by rakaur** [comment]
I219-LM still doesn't work.

**Comment by rakaur** [comment]
Hey, that was valuable information and definitely not "disruptive." I'm letting you know I219-LM https://pcilookup.com/?ven=8086&dev=0d4c&action=submit still doesn't work. I guess it's disruptive because this issue is limited to I219-V. I understand completely. How off-topic of me. I'll file a new issue.
