### ISSUE TITLE
TCP Session drops since 20.1.4

### ISSUE THREAD

**Issue by DarkSunOne** [opnsense/src#58]
Hello everyone,

since the update to 20.1.4 we encounter strange connection issues.

It seems, that valid tcp sessions gets dropped randomly, and all further packets show up with TCP:FA, TCP:FPA and TCP:RA (blocked) on the firewall.

This is totally annoying because SSH sessions are freezing, JetBrains Software neeeds to be reopened for automatic uploads, various online streams suddenly stocks and so on. 
The disconnects usually occurs every 1 to 5 minutes.

The problem also occurs from one LAN on the OpnSense to an other LAN.

I searched a lot, and have absolutely no idea what could cause this problem.
Before the update to 20.1.4 everything worked without any problem.

Anyone an idea?
I am desperate and need a stable internet connection to work :-(

**Comment by fichtner** [comment]
Hi @DarkSunOne,

What was the last known good version? I'm really not aware of anything recent (20.1.x) that would cause this. The likely candidates are hardware, switches, cables in these weird cases...


Cheers,
Franco

**Comment by DarkSunOne** [comment]
Hi @fichtner ,

my first thoughts where also that it could be a hardware problem.

My Opnsense is virtualized with proxmox, so i first tried to move the firewall to three different nodes, everywhere with the same results.

The second idea was, that it could be a problem with virtio, so i reconfigured the firewall, and removed all virtio interfaces, and pass-through my quad intel nic directly to the vm, so that the igb driver is user ... same result.

The Hardware is about 1 year old, also the switch is not older than a year.

The last known good version was 20.1.3.

I also use Sensei on my box, already tried to disable Sensei and IPS, no luck there.

Is there a easy way, to downgrade to 20.1.3, to see if this is really a version related problem?

Greets,
René

**Comment by DarkSunOne** [comment]
Its frustrating ... i spent nearly the whole day to find the issue.

Currently i am running a fresh installation of 20.1, with restored settings -> same result
Before i restored the settings, it seems quite good.

I will start from scratch and reconfigure everything :-(

**Comment by DarkSunOne** [comment]
Update:
i completely reinstalled my firewall with 20.1 and started to reconfigure everything from scratch.

So far there are no problems, but i still have a lot to reinstall and reconfigure.
Further i still didn't updated to 20.1.4

I will update this post with my progress, and hopefully find the cause of this wired problem.

**Comment by visualage** [comment]
I experienced a similar problem after upgrading to 20.1.4. After some research and experimentation, it appears to me that this is caused by a grouped gateway when one interface goes online and offline (in my case, it is an ipsec interface created by ipsec route-based tunnel, which somehow is flakey). Whenever the status of an interface in a group changed, all TCP connections are dropped, regardless if those TCP connections are routed via that grouped gateway or not.

I am not sure which one was changed from 20.1.3 to 20.1.4. It could be the behavior of the grouped gateway (start dropping all TCP connections when one interface goes online or offline), or the flakeness of ipsec tunnels.

**Comment by DarkSunOne** [comment]
@visualage ... well that sounds pretty interesting.

It seems that my setup is similar:

- Dual WANs used in a gateway group
- 4 Routed IPSEC tsunnel with static configured gateways

Currently my environment seems pretty stable, but i didnt updated to 20.1.4 yet, and also didn't configured my dual wan setup (needed a stable internet today for work)

I will try to update to 20.1.4 first and than configure my dual wan (with snapshots after each step)
Lets see if i can reproduce that.
But it looks like that there is the issue

**Comment by boistordu** [comment]
I can confirm the problem. The problem is how opnsense is managing gateways. 
There is no problem with a double WAN. The problem resides with the vpn connections.  Unless of course, one of the WAN connection is unstable.
Soi apparently it started with 20.1.4 and is still current to 21.1.5.

Normally what should happen is that WAN interface should get a special treatment as the unique and only WAN interface and exit door.

Let's say this scenario. You have like me a virtualized opnsense on your LAN. It's not an exit door to the whole network, just an exit door from some others VMs or others servers specifically connected to that firewall. And this firewall is acting as a firewall for those servers only, so you need to go through it to connect the servers whether it's inside the LAN or through the vpn connection that are publicly routables.
So you are connecting through SSH inside your LAN to this opnsense instance and also to those servers passing through this instance because of NATing on the WAN side of this instance of course.
if one of the links whether it's one of the WAN or one of the IPSEC tunnel or any tunnel at all which serves as a gateway, then the whole system goes down and you have a drop of connection and even a timeout of a seconds or 2 of the webmin.

What should happen is actually that each gateway should be treated separately. Or at least the one with lowest priority should be   the one that determine if the system is reachable or not. 
 
What actually happens is : You, the dev of opnsense, have actually grouped the whole gateways together and so Packet filter is determining on its own and reorganizing the gateways each time one goes down or is determined offline or with latency if you let the ip monitoring. And since it (pf system) is doing that, you have a timeout for the time it processes this and a cut of connection with the tcp connection like ssh.

so @fichtner could you reopen this ticket so that we can investigate this further and understand how to make this better?
